version: "3"

services:
  db:
    image: postgres:9.6-alpine
    ports:
      - '5431:5432'
    environment:
      # these are PG builtin env vars
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: boiler_room

    container_name: db_container